apiVersion: apps/v1 #类型为Namespace
kind: Namespace  #类型为Namespace
metadata:
  name: ns-test  #命名空间名称
  labels:
    name: label-test  #pod标签


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    app: go-project-service
    appName: go-project-service
  name: go-project-service
spec:
  type: NodePort
  ports:
    - name: go-project-service
      port: 8100    #服务(svc) 访问端口
      protocol: TCP
      targetPort: 3001 # pod （容器）端口
      nodePort: 30011 # pod （容器）端口
  selector:
    app: go-project
status:
  loadBalancer: {}